-- SQL to create a `resources` table for Altaura
-- Run this in Supabase SQL editor (Project -> SQL Editor) or via psql.

CREATE TABLE IF NOT EXISTS public.resources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text,
  price numeric(10,2),
  original_price numeric(10,2),
  status text NOT NULL DEFAULT 'free' CHECK (status IN ('paid','free','coming_soon')),
  cover_image_url text,
  external_link text,
  display_order integer DEFAULT 0,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Seed rows (cover_image_url left NULL so you can upload via admin UI)
INSERT INTO public.resources (title, description, status, price, original_price, external_link, display_order)
VALUES
('AI for Your Brand', 'A practical guide to building, showing up, and selling with AI tools that actually work, covering the exact tools and prompts to save you time without losing your brand voice.', 'paid', 3500, 8000, 'https://selar.com/11ig16p8s1', 1),
('The Brand Audit', 'A six part self audit to help you see exactly where your brand is losing trust, attention, and sales, and what to fix first.', 'free', 0, NULL, 'https://selar.com/8n3w37q418', 2),
('The Brand Identity Checklist', 'Thirty decisions that turn a business into a brand, laid out as a clear checklist you can work through at your own pace.', 'free', 0, NULL, 'https://selar.com/o881j16436', 3)
ON CONFLICT DO NOTHING;

-- NOTE: create a public Storage bucket (e.g. "insights-images") for cover image uploads.
-- In Supabase Console: Storage -> Create new bucket -> Set "Public" to true.
